name: Enable-Flows-and-branch-solution-with-spn-auth
# Export solution from DEV environment
#  unpack it and prepare, commit and push a git branch with the changes

on:
  workflow_dispatch:
    inputs:
      # Change this value
      solution_name:
        description: 'name of the solution to worked on from Power Platform'
        required: true
        default: LeaveRequestApp
       #Do Not change these values
      solution_exported_folder:
        description: 'folder name for staging the exported solution *do not change*'
        required: true
        default: out/exported/
      solution_folder:
        description: 'staging the unpacked solution folder before check-in *do not change*'
        required: true
        default: out/solutions/
      solution_target_folder: 
       description: 'folder name to be created and checked in *do not change*'
       required: true
       default: solutions/
env:
#edit your values here
  ENVIRONMENT_URL: 'https://dev-pporg.crm8.dynamics.com/'
  CLIENT_ID: '6daa83ee-0b91-4e08-a6b1-2c1b922bca58'
  TENANT_ID: '58517fc9-ef86-4031-823c-8ca6cff2365d'
permissions:
  contents: write
jobs:
  export-from-dev:
    runs-on: windows-latest
    # or you can say runs-on: ubuntu-latest
    env:
      RUNNER_DEBUG: 1

    steps:
    - uses: actions/checkout@v2
      with:
        lfs: true
    - name: Install Power Platform CLI (PAC)
      uses: microsoft/powerplatform-actions/actions-install@v1.4.0
      
    - name: who-am-i action
      uses: microsoft/powerplatform-actions/who-am-i@v1.4.0
      with:
        environment-url: ${{env.ENVIRONMENT_URL}}
        app-id: ${{env.CLIENT_ID}}
        client-secret: ${{ secrets.PowerPlatformSPN }}
        tenant-id: ${{env.TENANT_ID}}

    
     # Step 3: Enable Power Platform Flows
    - name: Enable Flow IsEmpty
      uses: microsoft/powerplatform-actions/enable-flow@v1
      with:
        environment-url: ${{ env.ENVIRONMENT_URL }}
        flow-name: 'IsEmpty'  
    

    - name: branch-solution, prepare it for a PullRequest
      uses: microsoft/powerplatform-actions/branch-solution@v1.4.0
      with:
        solution-folder: ${{ github.event.inputs.solution_folder}}/${{ github.event.inputs.solution_name }}
        solution-target-folder: ${{ github.event.inputs.solution_target_folder}}/${{ github.event.inputs.solution_name }}
        repo-token: ${{ secrets.patToken }}
        allow-empty-commit: true
